# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2026'
email: noel.mcloughlin@gmail.com
existing_license_file: ''
full_name: Noel McLoughlin
gh_action_docs_preview: true
gh_action_pypi: true
github_org: lmodel
license: Apache-2.0
project_description: NIST AI RMF - Generative AI Profile - LinkML Schema
project_name: nist-ai-600-1
project_slug: nist_ai_600_1

